name = "DynamicBoundspODEsPILMS"
uuid = "1c7daff2-9b32-4762-838b-ee2b1e32ee26"
authors = ["Matthew Wilhelm <matthew.wilhelm@uconn.edu>"]
version = "0.1.0"

[deps]

[compat]
julia = "~0.7, ~1.0, ~1.1, ~1.2, ~1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
